# Intrduction to NumPy


#### 1. Import NumPy under the name np.

In [1]:
# your code here
import numpy as np

#### 2. Print your NumPy version.

In [4]:
# your code here
np.version.version

'1.21.5'

#### 3. Generate a 2x3x5 3-dimensional array with random values. Assign the array to variable *a*.
**Challenge**: there are at least three easy ways that use numpy to generate random arrays. How many ways can you find?

In [55]:
# Method 1
np.random.seed(43)
a = np.random.random((2,3,5))

In [56]:
# Method 2
np.random.seed(43)
a = np.random.randn(2,3,5)

In [57]:
# Method 3
np.random.seed(43)
a = np.random.rand(2,3,5)

#### 4. Print *a*.


In [58]:
# your code here
a

array([[[0.11505457, 0.60906654, 0.13339096, 0.24058962, 0.32713906],
        [0.85913749, 0.66609021, 0.54116221, 0.02901382, 0.7337483 ],
        [0.39495002, 0.80204712, 0.25442113, 0.05688494, 0.86664864]],

       [[0.221029  , 0.40498945, 0.31609647, 0.0766627 , 0.84322469],
        [0.84893915, 0.97146509, 0.38537691, 0.95448813, 0.44575836],
        [0.66972465, 0.08250005, 0.89709858, 0.2980035 , 0.26230482]]])

#### 5. Create a 5x2x3 3-dimensional array with all values equaling 1. Assign the array to variable *b*.

In [59]:
# your code here
b = np.ones((5,2,3))

#### 6. Print *b*.


In [60]:
# your code here
b

array([[[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]]])

#### 7. Do *a* and *b* have the same size? How do you prove that in Python code?

In [62]:
# your code here
if a.shape == b.shape:
    print ("True")
else: 
    print ("False")

False


#### 8. Are you able to add *a* and *b*? Why or why not?


In [22]:
# your answer here
a + b
# No we can't add a and b because they don't have the same structure 

ValueError: operands could not be broadcast together with shapes (2,3,5) (5,2,3) 

#### 9. Transpose *b* so that it has the same structure of *a* (i.e. become a 2x3x5 array). Assign the transposed array to variable *c*.

In [63]:
# your code here
c = b.reshape((2,3,5))
c

array([[[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]],

       [[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]]])

#### 10. Try to add *a* and *c*. Now it should work. Assign the sum to variable *d*. But why does it work now?

In [64]:
# your code/answer here
d = a + c 
#both a and c have the same size 

#### 11. Print *a* and *d*. Notice the difference and relation of the two array in terms of the values? Explain.

In [67]:
# your code/answer here
print('this is a: \n', a)
print('')
print('this is d: \n', d)

# we can notice the values in d are the values in a + 1 

this is a: 
 [[[0.11505457 0.60906654 0.13339096 0.24058962 0.32713906]
  [0.85913749 0.66609021 0.54116221 0.02901382 0.7337483 ]
  [0.39495002 0.80204712 0.25442113 0.05688494 0.86664864]]

 [[0.221029   0.40498945 0.31609647 0.0766627  0.84322469]
  [0.84893915 0.97146509 0.38537691 0.95448813 0.44575836]
  [0.66972465 0.08250005 0.89709858 0.2980035  0.26230482]]]

this is d: 
 [[[1.11505457 1.60906654 1.13339096 1.24058962 1.32713906]
  [1.85913749 1.66609021 1.54116221 1.02901382 1.7337483 ]
  [1.39495002 1.80204712 1.25442113 1.05688494 1.86664864]]

 [[1.221029   1.40498945 1.31609647 1.0766627  1.84322469]
  [1.84893915 1.97146509 1.38537691 1.95448813 1.44575836]
  [1.66972465 1.08250005 1.89709858 1.2980035  1.26230482]]]


#### 12. Multiply *a* and *c*. Assign the result to *e*.

In [68]:
# your code here
e = a*c

#### 13. Does *e* equal to *a*? Why or why not?


In [69]:
# your code/answer here
e == a
# e is equal a because a is multiplied with 1 so it generates the same result as a

array([[[ True,  True,  True,  True,  True],
        [ True,  True,  True,  True,  True],
        [ True,  True,  True,  True,  True]],

       [[ True,  True,  True,  True,  True],
        [ True,  True,  True,  True,  True],
        [ True,  True,  True,  True,  True]]])

#### 14. Identify the max, min, and mean values in *d*. Assign those values to variables *d_max*, *d_min* and *d_mean*.

In [70]:
# your code here
d_max = np.max(d) 
print('max is : \n', d_max)
d_min = np.min(d) 
print('min is : \n', d_min)
d_mean = np.mean(d)
print('mean is : \n', d_mean)



max is : 
 1.971465091435388
min is : 
 1.0290138244243603
mean is : 
 1.476900205884057


#### 15. Now we want to label the values in *d*. First create an empty array *f* with the same shape (i.e. 2x3x5) as *d* using `np.empty`.


In [71]:
# your code here
f = np.empty(shape=(2,3,5))
f

array([[[1.11505457, 1.60906654, 1.13339096, 1.24058962, 1.32713906],
        [1.85913749, 1.66609021, 1.54116221, 1.02901382, 1.7337483 ],
        [1.39495002, 1.80204712, 1.25442113, 1.05688494, 1.86664864]],

       [[1.221029  , 1.40498945, 1.31609647, 1.0766627 , 1.84322469],
        [1.84893915, 1.97146509, 1.38537691, 1.95448813, 1.44575836],
        [1.66972465, 1.08250005, 1.89709858, 1.2980035 , 1.26230482]]])

#### 16. Populate the values in *f*. 

For each value in *d*, if it's larger than *d_min* but smaller than *d_mean*, assign 25 to the corresponding value in *f*. If a value in *d* is larger than *d_mean* but smaller than *d_max*, assign 75 to the corresponding value in *f*. If a value equals to *d_mean*, assign 50 to the corresponding value in *f*. Assign 0 to the corresponding value(s) in *f* for *d_min* in *d*. Assign 100 to the corresponding value(s) in *f* for *d_max* in *d*. In the end, f should have only the following values: 0, 25, 50, 75, and 100.

**Note**: you don't have to use Numpy in this question.

In [72]:
# your code here

f[np.where((d_min<d) & (d<d_mean))] = 25
f[np.where((d_mean<d) & (d<d_max))] = 75
f[np.where(d==d_mean)] = 50
f[np.where(d==d_min)] = 0
f[np.where(d==d_max)] = 100



#### 17. Print *d* and *f*. Do you have your expected *f*?
For instance, if your *d* is:
```python
[[[1.85836099, 1.67064465, 1.62576044, 1.40243961, 1.88454931],
[1.75354326, 1.69403643, 1.36729252, 1.61415071, 1.12104981],
[1.72201435, 1.1862918 , 1.87078449, 1.7726778 , 1.88180042]],
[[1.44747908, 1.31673383, 1.02000951, 1.52218947, 1.97066381],
[1.79129243, 1.74983003, 1.96028037, 1.85166831, 1.65450881],
[1.18068344, 1.9587381 , 1.00656599, 1.93402165, 1.73514584]]]
```
Your *f* should be:
```python
[[[ 75.,  75.,  75.,  25.,  75.],
[ 75.,  75.,  25.,  25.,  25.],
[ 75.,  25.,  75.,  75.,  75.]],
[[ 25.,  25.,  25.,  25., 100.],
[ 75.,  75.,  75.,  75.,  75.],
[ 25.,  75.,   0.,  75.,  75.]]]
```

In [74]:
# your code here
print('d is \n\n: ', d)
print('')
print('f is  \n\n: ', f)

d is 

:  [[[1.11505457 1.60906654 1.13339096 1.24058962 1.32713906]
  [1.85913749 1.66609021 1.54116221 1.02901382 1.7337483 ]
  [1.39495002 1.80204712 1.25442113 1.05688494 1.86664864]]

 [[1.221029   1.40498945 1.31609647 1.0766627  1.84322469]
  [1.84893915 1.97146509 1.38537691 1.95448813 1.44575836]
  [1.66972465 1.08250005 1.89709858 1.2980035  1.26230482]]]

f is  

:  [[[ 25.  75.  25.  25.  25.]
  [ 75.  75.  75.   0.  75.]
  [ 25.  75.  25.  25.  75.]]

 [[ 25.  25.  25.  25.  75.]
  [ 75. 100.  25.  75.  25.]
  [ 75.  25.  75.  25.  25.]]]


#### 18. Bonus question: instead of using numbers (i.e. 0, 25, 50, 75, and 100), use string values  ("A", "B", "C", "D", and "E") to label the array elements. For the example above, the expected result is:

```python
[[[ 'D',  'D',  'D',  'B',  'D'],
[ 'D',  'D',  'B',  'B',  'B'],
[ 'D',  'B',  'D',  'D',  'D']],
[[ 'B',  'B',  'B',  'B',  'E'],
[ 'D',  'D',  'D',  'D',  'D'],
[ 'B',  'D',   'A',  'D', 'D']]]
```
**Note**: you don't have to use Numpy in this question.

In [ ]:
# your code here
